apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-main
  template:
    metadata:
      labels:
        app: arcadia-main
    spec:
      containers:
        - name: arcadia-main
          image: yalmashad/arcadia-main:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-backend

  template:
    metadata:
      labels:
        app: arcadia-backend
    spec:
      containers:
        - name: arcadia-backend
          image: yalmashad/arcadia-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-app2

  template:
    metadata:
      labels:
        app: arcadia-app2
    spec:
      containers:
        - name: arcadia-app2
          image: yalmashad/arcadia-app2:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-app3

  template:
    metadata:
      labels:
        app: arcadia-app3
    spec:
      containers:
        - name: arcadia-app3
          image: yalmashad/arcadia-app3:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
